# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Install dependencies
WORKDIR /app
COPY pyproject.toml uv.lock ./
# Install runtime dependencies
RUN pip install --no-cache-dir mcp>=1.9.3 requests python-dotenv

# Copy application code
COPY . .

# Expose port if needed (not needed for stdio)

# Set default command
CMD ["python", "server.py"]
