[project]
name = "congress-gov-mcp"
version = "0.1.0"
description = "Unofficial MCP Server for the Congress.gov API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.9.3",
    "requests>=2.32.3",
]
